### ISSUE TITLE
Duplicate Artwork?

### ISSUE THREAD

**Issue by five0five** [Trikzon/Gingerbread#4]
I think the title explains what I'm getting at here, I've found some *similarities* to other mods I've installed. According the mod spotlight you made, the gingerbread sprite was donated by someone else and you modified the legs, interestingly enough, the aether mod has the same gingerbread man with different legs. There are also several similarities to Joshua's Christmas mod and I've provided an imgur link with some examples:
Imgur: https://imgur.com/a/h7hXrZy
Aether: https://minecraft.curseforge.com/projects/the-aether-mod
Joshua's Christmas mod: https://minecraft.curseforge.com/projects/joshuas-christmas-mod

**Comment by Trikzon** [comment]
Sorry for just seeing this now.
1. This mod isn't even a thing anymore... so whatever
2. The icicle, stocking, and gingerbread I personally made without reference to other textures
3. The gingerbread was made by someone I knew. I hadn't looked if he copied anyone else before so and personally edited the legs from what he sent me (he sent me pretty much exactly what you sent... which disappoints me)
